ukniga_NEW/slider/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # Добавьте URL-путь для отображения слайдера с параметром slider_id
    path('<str:slider_id>/', views.slider_view, name='slider_view'),
]

ukniga_NEW/ukniga_NEW/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings #импортируем настройки конфига
from django.conf.urls.static import static
from ckeditor_uploader import views as ckeditor_uploader_views
from filebrowser.sites import site


urlpatterns = [
        
    path('ckeditor/', include('ckeditor_uploader.urls')), #путь к ckeditor
    path('summernote/', include('django_summernote.urls')),
    path('', include('subscriptions.urls')), #путь к форме подписки
    path('admin/filebrowser/', site.urls),
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')), #добавляем путь к allauth
    path('captcha/', include('captcha.urls')), #добавляем путь к капче
    path('', include('userprofile.urls')),
    path('', include('post_page.urls')), #include принимает набор маршрутов из файла блог пэйдж\
    path('', include('slider.urls')), #include принимает набор маршрутов из файла блог пэйдж\
    path('tinymce/', include('tinymce.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #дает доступ к медиа в режиме дебагинга

ukniga_NEW/post_page/models.py
from django.db import models
from slugify import slugify
from django_ckeditor_5.fields import CKEditor5Field
from django.urls import reverse
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import User
import os
from django.utils import timezone
from ckeditor.fields import RichTextField
from django_summernote.fields import SummernoteTextField
from django.core.exceptions import ValidationError
from django.conf import settings
from django_q.tasks import schedule
from .tasks import check_and_publish_post
from django.db import connection




User.add_to_class('subscribe', models.BooleanField(default=False))


class MyPermissions(models.Model):
    class Meta:
        permissions = [
            ("can_view_content", "Can view content"),
            # Добавьте здесь другие разрешения, если нужно
        ]


#Файловый браузер
def upload_to_folder(instance, filename):
    return f'{instance.upload_folder}/{filename}'

class MyFile(models.Model):
    name = models.CharField(max_length=100)
    file = models.FileField(upload_to=upload_to_folder)
    wrap_image = models.BooleanField(default=False, verbose_name='Картинка с обтеканием')
    upload_folder = models.CharField(max_length=100, default='uploads', verbose_name='Папка загрузки')

    class Meta:
        verbose_name = "Файл"
        verbose_name_plural = "Файловый браузер"
# class MyFile(models.Model):
#     name = models.CharField(max_length=100)
#     file = models.FileField(upload_to='uploads/')

#     def save(self, *args, **kwargs):
#         original_filename = self.file.name
#         extension = os.path.splitext(original_filename)[1]
#         # Сохраняем только расширение оригинального файла
#         self.file.name = self.name + extension
#         super(MyFile, self).save(*args, **kwargs)
        
#     class Meta:
#         verbose_name = "Файл"
#         verbose_name_plural = "Файловый браузер"


class Category(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=300, blank=True)
    slug = models.SlugField(max_length=100, unique=True, blank=True)
    image = models.ImageField(upload_to='images/category_img', blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.name



class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    
    class Meta:
        verbose_name = "Тег"
        verbose_name_plural = "Теги"

    def __str__(self):
        return self.name
    



#данные о записи
class Post(models.Model):
    MONTH_CHOICES = [
        ('Январь', 'Январь'), ('Январь/Февраль', 'Январь/Февраль'), ('Февраль', 'Февраль'), ('Март', 'Март'),
        ('Апрель', 'Апрель'), ('Май', 'Май'), ('Июнь', 'Июнь'),
        ('Июль', 'Июль'), ('Июль/Август', 'Июль/Август'), ('Август', 'Август'), ('Сентябрь', 'Сентябрь'),
        ('Октябрь', 'Октябрь'), ('Ноябрь', 'Ноябрь'), ('Декабрь', 'Декабрь')
    ]
    
    title = models.CharField('Заголовок записи', max_length=200)
    description = models.TextField('Краткое описание', max_length=200)
    text = SummernoteTextField()
    page = models.IntegerField('Номер страницы в журнале', default=None, blank=True, null=True)
    img = models.ImageField('Главное изображение поста', upload_to='images/%Y/%m-%d')
    img_card = models.ImageField('Фото для карточки категорий', upload_to='images/%Y/%m-%d', default=None)
    slug = models.SlugField(max_length=255, unique=True, blank=True)
    category = models.ManyToManyField(Category, related_name='Category')
    tags = models.ManyToManyField('Tag', related_name='posts')
    year = models.IntegerField('Год', validators=[MinValueValidator(2000), MaxValueValidator(2100)])
    month = models.CharField('Месяц', max_length=20, choices=MONTH_CHOICES)
    image = models.ImageField('Обложка архива', upload_to='date_images/', default='', blank=True, null=True)
    is_paid = models.BooleanField('Платный материал', default=False)
    is_arhive = models.BooleanField('Архив', default=False)
    published_date = models.DateTimeField('Дата публикации', null=True, blank=True)
    is_published = models.BooleanField('Опубликовано', default=False)
    is_featured = models.BooleanField('Выводить на главной', default=False)


    @staticmethod
    def search(query):
        # Разбиваем запрос на отдельные слова и формируем строку с учетом весов полей
        words = query.split()
        query_with_weights = ' '.join([f'+{word}' for word in words])

        # Формируем условие для поиска, где оба слова должны встречаться в одном поле
        query_condition = ' '.join([f'(+{word})' for word in words])

        # Составляем SQL запрос с учетом весов полей и условия поиска
        sql_query = (
            "SELECT *, MATCH(title, description, text) AGAINST (%s IN BOOLEAN MODE) AS relevance "
            "FROM post_page_post "
            "WHERE MATCH(title, description, text) AGAINST (%s IN BOOLEAN MODE) AND "
            f"(MATCH(title, description, text) AGAINST ('{query_condition}' IN BOOLEAN MODE)) AND is_published = True "
            "ORDER BY relevance DESC"
        )

        return Post.objects.raw(sql_query, [query_with_weights, query_with_weights])


        

    def clean(self):
        if self.is_arhive and not self.image:
            raise ValidationError("Поле: Обложка архива - обязательно для архивной статьи.")    

    CARD_DISPLAY_CHOICES = [
        ('default', 'Фото + Заголовок'),
        ('fullscreen', 'Фото на всю ширину с оверфлоу + Заголовок поверх фото'),
        ('NoFoto', 'Без фото'),
    ]

    card_display = models.CharField('Вид карточки', max_length=20, choices=CARD_DISPLAY_CHOICES, default='default')

    def get_id(self):
        return self.id
    get_id.short_description = 'ID'

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'


    def save(self, *args, **kwargs):
        # Если slug не был указан явно, генерируем его на основе title
        if not self.slug:
            self.slug = slugify(self.title)

        # Текущее время
        local_time = timezone.localtime(timezone.now())

        # Логика публикации
        if self.is_published:
            if self.published_date and self.published_date > local_time:
                # Если время публикации в будущем, делаем пост невидимым на публичных страницах
                self.is_published = False
            else:
                # Время текущее или прошлое, пост публикуется
                self.is_published = True
        else:
            # Если чекбокс не выбран или снят, пост не виден на публичных страницах
            self.is_published = False

        # Сохраняем изменения
        super(Post, self).save(*args, **kwargs)

        # Планирование задачи на будущее время, если нужно
        if self.published_date and self.published_date > timezone.localtime():
            schedule('post_page.tasks.check_and_publish_post', self.id, schedule_type='O', next_run=self.published_date)

        # Логика снятия с публикации
        if self.unpublished_date:
            if self.unpublished_date <= local_time:
                # Если дата окончания публикации в прошлом или настоящем, снимаем пост с публикации
                self.is_published = False
                super(Post, self).save(*args, **kwargs)
            else:
                # Планирование задачи на будущее время для снятия с публикации
                schedule('post_page.tasks.check_and_unpublish_post', self.id, schedule_type='O', next_run=self.unpublished_date)
        

    def get_image_absolute_url(self):
        return f"{settings.SITE_URL}{self.img.url}"
        
    
    def get_absolute_url(self):
        # Используем URL-паттерн 'post_detail' если у поста есть slug и хотя бы одна категория
        if self.slug and hasattr(self, 'category') and self.category.exists():
            category_slug = self.category.all().order_by('slug').first().slug
            return reverse('post_detail', kwargs={'category_slug': category_slug, 'slug': self.slug})

        # Используем URL-паттерн 'posts_by_year' если у поста есть дата
        if hasattr(self, 'date') and self.date:
            return reverse('posts_by_year', kwargs={'year': self.date.year, 'month': self.date.month})

        # Возвращаем URL для просмотра деталей поста или платного контента в зависимости от подписки автора
        if hasattr(self, 'author') and self.author.subscribe:
            return reverse('post_detail', kwargs={'post_id': self.id})
        else:
            return reverse('paid')

        # Если ни одно из условий не выполнено, можно вернуть главную страницу или другой стандартный URL
        return reverse('home')
 
    
    #отображение записей в админке?    
    def __str__(self):
        return f'{self.title}{self.description}'
    
    
    
    
class FavoritePost(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user.username} - {self.post.title}"
    
    
class StaticTemplate(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name="Название шаблона")
    content = SummernoteTextField(verbose_name="Содержимое")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Статический шаблон"
        verbose_name_plural = "Статические шаблоны"

ukniga_NEW/templates/about.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% load slider_tags %}

<div class="container">
    <div class="row">

        <div class="col-3 d-none d-xl-block my-4">
            <p><a href="#auditory">Читательская аудитория</a></p>
            <p><a href="#rubriki">Рубрики</a></p>
            <p><a href="#redsovet">Редакционный совет</a></p>
            <p><a href="#dostizheniya">Наши достижения</a></p>

            <!-- Навменю -->
            {% include 'includes/menu-all.html' %}
            
        </div>

        <div class="col-12 col-xl-9 mt-4">

            
            <!-- Первый баннер -->
            <div class="mb-3" id="banner-head">
                {% get_banners 'header' as banners %}
            
                {% for banner in banners %}
                    {% if banner.show_on_main and request.path == '/' %}
                        {% include "banner.html" %}
                    {% elif not banner.show_on_main %}
                        {% include "banner.html" %}
                    {% endif %}
                {% endfor %}

            </div>

            {{ content|safe }}

        </div>
    
    </div>
</div>

{% endblock %}

ukniga_NEW/templates/arhiv-list.html
{% extends 'base.html' %}
{% block content %}
{% load slider_tags %}

    <div class="container" style="min-height: 2000px;">
        <div class="row justify-content-center">

            <!-- секция слева -->
            <div class="col-xl-3 mt-4"> 

                    <!-- Нав меню слева -->
                    <div class="div d-none d-xl-block">
                        {% include 'includes/menu_va.html' %}
                    </div>

            </div>


            <!-- Первая секция -->
            <div class="col-12 col-xl-9 mt-4">
                <div class="row">


                    <!-- Первый баннер -->
                    <div class="mb-3" id="banner-head">
                        {% get_banners 'header' as banners %}
                    
                        {% for banner in banners %}
                            {% if banner.show_on_main and request.path == '/' %}
                                {% include "banner.html" %}
                            {% elif not banner.show_on_main %}
                                {% include "banner.html" %}
                            {% endif %}
                        {% endfor %}
                    
                    </div>

                    <div class="container">
                        <div class="d-flex justify-content-center align-items-center">
                            <div class="d-block col-12 d-xl-none col-sm-4 text-center">
                                <h5 class="mt-3" style="font-weight: 15px;">Выберите год</h5>
                                <div class="card-body">
                                    <form method="get" action="">
                                        {{ form.year }}
                                        <button type="submit" class="btn btn-custom rounded-0 my-2">Показать обложки</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <hr>
                    </div>                    


                    <!-- Обложки с картинками -->
                    {% for month, posts in posts_by_month.items %}
                        <div class="col-lg-4 col-sm-6 col-12 text-center">



                            <h5 class="my-3">{{ month }}</h5>
                            {% for post in posts %}
                                <a href="{% url 'posts_by_year' %}?year={{ selected_year }}&month={{ month }}">
                                    <img src="{{ post.image.url }}" alt="{{ post.title }}" class="img-fluid w-75">
                                </a>
                            {% endfor %}
                        </div>
                    {% endfor %}


                </div>    
            </div>

        </div>
    </div>



{% endblock %}

ukniga_NEW/templates/arhive_page.html
{% extends 'base.html' %}
{% block content %}
{% load slider_tags %}
{% load static %}




    <!-- <div class="container">
        <div class="row g-3">
            <h1>Архив</h1>
            <div class="col-sm-6">


                        <form method="get" action="{% url 'posts_by_year' %}">
                            <label for="{{ form.year.id_for_label }}">Год:</label>
                            {{ form.year }}
                                           
            </div>


            <div class="col-sm-6">          
                        
                            <label for="{{ form.month.id_for_label }}">Месяц:</label>
                            {{ form.month }}
                        
            </div>              

            <div class="col-12">

                            <label for="{{ form.is_arhive.id_for_label }}">Архив:</label>
                            {{ form.is_arhive }}

            </div>


            <div class="col-12">

                        <button type="submit" class="btn btn-primary">Поиск</button>

            </div>
            </div>
                        </form>

            

    </div>
    
    
    
    <div class="container mt-4">           
        <div class="row">
            <div class="col-12">



            </div> 
        </div>
    </div> -->



    
    <div class="container" style="min-height: 2500px;">
        <div class="row justify-content-center">

            <!-- секция слева -->
            <div class="col-xl-3 mt-4">

                <div class="div d-none d-xl-block">
                    <!-- Нав меню слева -->
                    {% include 'includes/menu-arhive.html' %}
                </div>   


            </div>



            <!-- секция справа -->
            <div class="col-12 col-xl-9 mt-4">

                <!-- Первый баннер -->
                <div class="mb-3" id="banner-head">
                    {% get_banners 'header' as banners %}
                
                    {% for banner in banners %}
                        {% if banner.show_on_main and request.path == '/' %}
                            {% include "banner.html" %}
                        {% elif not banner.show_on_main %}
                            {% include "banner.html" %}
                        {% endif %}
                    {% endfor %}
                
                </div>

                <h5>Содержание номера</h5>
                <hr>
                
                {% for post in posts %}

                <!-- Карточка -->
                <div id="card" class="card mb-3 border-bottom border-0 rounded-0">
                    <div class="row g-0">
        
        
                        <!-- Первый блок -->
                        <div class="col-md-1 d-flex flex-column">
                            <div class="card-body" style="display: flex; flex-direction: column; height: 100%;">

                            <div class="container d-flex justify-content-center align-items-center">
                                <div class="ya-share2" data-services="vkontakte,telegram" data-color-scheme="blackwhite" data-shape="normal" data-title="{{ post.title }}" data-description="{{ post.description }}" data-image="{{ post.img }}"></div>
                            </div>


                              <div class="text-center" style="margin-top: auto;">
                                <p class="my-1" style="font-size: 10px;">Номер страницы</p><h5>{{ post.page }}</h5>
                              </div>
                            </div>
                        </div>
        
                        <!-- Блок с фото -->
                        <div class="col-md-5 d-flex align-items-center justify-content-center" style="overflow: hidden;">
                          <img src="{{ post.img_card.url }}" class="img-fluid w-100 h-100" style="object-fit: cover" alt="{{ post.title }}">
                        </div>
        
        
                        <!-- Блок с текстом -->
                        <div class="col-md-6 ps-2">
                            <div class="card-body d-flex flex-column" style="height: 100%;">
        
                                
                              <div class="flex-fill">
                                <div class="row mb-4">
                                    <a id="full-txt" style="font-size: 11px;" href="">{{ post.published_date|date:"d-m-Y" }}</a>
                                    {% if post.category.count > 1 %}
                                        <a id="full-txt" style="font-size: 15px; font-family: 'Play';" href="{% url 'category_posts' category_slug=post.category.last.slug %}">Рубрика: {{ post.category.last.name }}</a>
                                    {% else %}
                                        <a id="full-txt" style="font-size: 15px; font-family: 'Play';" href="{% url 'category_posts' category_slug=post.category.first.slug %}">Рубрика: {{ post.category.first.name }}</a>
                                    {% endif %} 
                                </div>
                              </div>
        
                                <hr>
        
        
                              <div class="text-card">
                                <h5>{{ post.title }}</h5>
        
                                <p>{{ post.description }}</p>
                              </div>
        
                              
                              <div class="flex-fill">
                                <div class="container mt-5" style="background-image: linear-gradient(45deg, #95efff2a, #ecbdff38);">
                                    <div class="row d-flex align-items-center">
                                        
                                        <div class="col">
                                            <a href="{% if not post.is_paid or user.is_authenticated and user.subscribe %}
                                            {% if post.category.count > 1 %}
                                                {% url 'post_detail_multiple_categories' category_slug=post.category.all.0.slug secondary_category_slug=post.category.last.slug slug=post.slug %}
                                            {% else %}
                                                {% url 'post_detail' category_slug=post.category.first.slug slug=post.slug %}
                                            {% endif %}
                                        {% else %}
                                            {% url 'paid_view' %}
                                        {% endif %}" class="btn btn-custom rounded-0 my-2">Читать</a>
                                        </div>
        
                                        <div class="col text-center">
                                            <form method="post" action="{% url 'manage_favorite' post.id %}"id="favoriteForm">
                                                {% csrf_token %}
                                                {% if is_favorite %}
                                                    <p>Уже добавлен в избранное</p>
                                                {% else %}
                                                    <button type="submit" id="favoriteButton" name="add_to_favorite" class="btn">
                                                        <img src="{% static 'empty-1.png' %}" style="width: 15px;" alt="В избранном">
                                                    </button>
                                                {% endif %}
                                            </form>
                                        </div>
        
                                        <div class="col text-center" style='font-size: 12px'>
                                            {% for tag in post.tags.all|slice:":1" %}
                                                <a id="full-txt" href="{% url 'tags' tag.name %}">{{ tag.name }}</a>
                                            {% endfor %}
                                        </div>
                                    
                                    
                                    </div>
                                </div>
                              </div>  
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Конец карточки --> 

            {% endfor %}   


            </div>
        </div>
    </div>



{% endblock %}

ukniga_NEW/templates/banner.html
<div id="banner-desc-{{ banner.id }}" class="banner d-none d-lg-block">
    <a href="{{ banner.url }}">
        <img src="{{ banner.image_desktop.url }}" alt="{{ banner.title }}" class="img-fluid">
    </a>
</div>

<div id="banner-tab-{{ banner.id }}" class="banner d-none d-sm-block d-lg-none">
    <a href="{{ banner.url }}">
        <img src="{{ banner.image_tablet.url }}" alt="{{ banner.title }}" class="img-fluid">
    </a>
</div>

<div id="banner-mob-{{ banner.id }}" class="banner d-block d-sm-none">
    <a href="{{ banner.url }}">
        <img src="{{ banner.image_mobile.url }}" alt="{{ banner.title }}" class="img-fluid">
    </a>
</div>

ukniga_NEW/templates/forautors.html
{% extends 'base.html' %}
{% block content %}
{% load slider_tags %}
{% load static %}

<div class="container">
    <div class="row">

        <!-- секция слева -->
        <div class="col-3 d-none d-xl-block mt-4">
            <!-- Нав меню -->
            {% include 'includes/menu-all.html' %}
        </div>  


        <div class="col-12 col-xl-9 mt-4">

            <!-- Первый баннер -->
            <div class="mb-3" id="banner-head">
                {% get_banners 'header' as banners %}
            
                {% for banner in banners %}
                    {% if banner.show_on_main and request.path == '/' %}
                        {% include "banner.html" %}
                    {% elif not banner.show_on_main %}
                        {% include "banner.html" %}
                    {% endif %}
                {% endfor %}

            </div>

            
            <!-- Редактируемый контент из админки -->
            {{ content|safe }}   

        </div>


    </div>
</div>

{% endblock %}

ukniga_NEW/templates/paid.html
{% extends 'base.html' %}
{% block content %}
{% load slider_tags %}
{% load static %}

<div class="container">
    <div class="row">
        <div class="col-3 d-none d-xl-block mt-4">
            <!-- Нав меню -->
            {% include 'includes/menu-all.html' %}
        </div>

        <div class="col-12 col-xl-9 mt-4">
            

            <!-- Первый баннер -->
            <div class="mb-3" id="banner-head">
                {% get_banners 'header' as banners %}
            
                {% for banner in banners %}
                    {% if banner.show_on_main and request.path == '/' %}
                        {% include "banner.html" %}
                    {% elif not banner.show_on_main %}
                        {% include "banner.html" %}
                    {% endif %}
                {% endfor %}

            </div>

            
            <!-- Редактируемый контент из админки -->
            {{ content|safe }}   
        
        
        </div>
    </div>
</div>

{% endblock %}

ukniga_NEW/templates/password_form.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <html lang="en">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css" media="all" />
	{% comment %} <link rel="stylesheet" href="https://unpkg.com/flickity@2/dist/flickity.min.css"> {% endcomment %}
	<link rel="stylesheet" href="{% static 'css/slider.css' %}" type="text/css" media="all" />
	<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" />
    <link rel="shortcut icon" href="css/images/favicon.ico" />
    <meta name='description' content='{{ post.description }}'>
	

</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col d-flex justify-content-center">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Войти</button>
                </form>
            </div>
        </div>
    </div>
</body>

ukniga_NEW/templates/profile.html
{% extends 'base-account.html' %}
{% block content %}
{% load static %}

 <!-- Обложка -->
 <div class="container mt-4">
  <div class="row">
    <div class="col d-flex align-items-center justify-content-center" style="height: 300px;">
      {% if profile.cover_photo %}
        <img class="w-100 h-100 rounded" style="object-fit: cover;" src="{{ profile.cover_photo.url }}" alt="Обложка профиля">
      {% else %}
        <!-- Если обложка профиля не загружена, отобразить дефолтное изображение из папки медиа -->
        <img class="w-100 h-100 rounded" style="object-fit: cover;" src="{% static 'photo_2024-04-17_10-39-51.jpg' %}" alt="Дефолтная обложка">
      {% endif %}
    </div>
  </div>  
</div>


<div class="container mt-5">
  <div class="row">

      <!--Левое меню -->
      <div class="col-lg-3 mb-5">
        <h5>Профиль пользователя</h5>
        <hr>
        <div class="photo-profile mb-3 d-flex align-items-center justify-content-center">
          {% if profile.photo %}
              <img class="w-75" src="{{ profile.photo.url }}" alt="Фото профиля">
          {% else %}
              <!-- Если фото профиля не загружено, отобразить дефолтное фото из папки медиа -->
              <img class="w-75" src="{% static 'image_2024-04-17_10-43-44.png' %}" alt="Дефолтное фото">
          {% endif %}
        </div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ profile_form.as_p }}
            <button type="submit" class="btn btn-custom">Сохранить изменения</button>
        </form>
        <hr>
        <form method="post" action="{% url 'account_change_password' %}">
          {% csrf_token %}
          {{ password_change_form.as_p }}
          <button type="submit" class="btn btn-custom">Сменить пароль</button>
        </form>
        <a href="{% url 'account_logout' %}" class="btn btn-custom rounded-0 my-2">Выйти</a>
      </div>  

      <div class="col-lg-9">
        <h5>Избранное</h5>
        <hr>

        <!-- Контейнер -->
        <div class="container">
          <div class="row">
            {% if request.user.favoritepost_set.all %}
              {% for favorite_post in request.user.favoritepost_set.all %}
                <div class="card p-0 m-1" style="width: 230px;">
                  <img src="/media/{{ favorite_post.post.img }}" class="card-img-top img-fluid w-100" style="overflow: hidden;">
                  <div class="card-body d-flex flex-column justify-content-between" style="height: 150px;">
                    <h5 style="font-size: 15px;"><a href="{% url 'post_detail' category_slug=favorite_post.post.category.first.slug slug=favorite_post.post.slug %}">
                      {{ favorite_post.post.title }}
                    </a></h5>
                    <form method="post" action="{% url 'manage_favorite' favorite_post.post.id %}">
                      {% csrf_token %}
                      <button type="submit" class="btn btn-custom" name="remove_from_favorite">Удалить из избранного</button>
                    </form>
                  </div>
                </div>
              {% endfor %}
            {% else %}
              <h5 style="font-size: 15px;">Здесь будут материалы, которые вы добавите в Избранное</h5>
            {% endif %}
          </div>
        </div>
        <!-- Конец Контейнер -->

      </div>


  </div>
</div>  




{% endblock %}

ukniga_NEW/templates/slider_template.html
<!DOCTYPE html>
<html>
    <body>
        {% if slider %}
            {{ slider.generate_slider_html|safe }}
        {% else %}
            <!-- Обработка случая, когда слайдер не найден -->
        {% endif %}
    </body>
</html>